version: "3"
services:
  app:
    build: .
    volumes:
      - ./app/:/app
    ports:
      - 19000-19002:19000-19002
      - 19006:19006
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.100.116
    command: expo start --web